### ISSUE TITLE
Allow scheduling `ClusterVersion` changes

### ISSUE THREAD

**Issue by bastjan** [appuio/openshift-upgrade-controller#80]
### Summary

**As** cluster maintenance engineer\
**I want** to make it change `ClusterVersion` parameters during maintenance or when scheduling upgrades\
**So that** I can schedule minor version changes.

### Context

Scheduling minor version changes is currently not possible using the controller. Minor versions are uprgaded by switching over the `.spec.channel` of the [controller managed](https://github.com/appuio/openshift-upgrade-controller/blob/1ec2b3dcfec9eb0dc47b1ca4098a9034a404efdd/api/v1beta1/clusterversion_types.go#L22) `ClusterVersion` manifest.

We need a way to schedule those minor version changes before a scheduled upgrade.

### Out of Scope

- OCP admin ack https://github.com/appuio/component-openshift-upgrade-controller/issues/51

### Further links

- https://kb.vshn.ch/oc4/explanations/decisions/ocp-minor-version-tracking.html

### Acceptance Criteria

- Architecture docs updated https://kb.vshn.ch/oc4/references/architecture/upgrade_controller.html
- The release channel in the controller managed `ClusterVersion` can be changed at a given timestamp.
- A metric with the change timestamp exists.

### Scheduled patches

```yaml
apiVersion: managedupgrade.appuio.io/v1beta1
kind: ClusterVersion
metadata:
  name: version
  namespace: appuio-openshift-upgrade-controller
spec:
  template:
    spec:
      channel: stable-4.14
      clusterID: XXX
  patches:
    - from: "2024-07-12T00:00:00Z"
      patch:
        spec:
          channel: stable-4.15
```
